name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/2 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: blackchoey/stale@chyuan/debug
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message2'
        stale-issue-label: 'need attention'
        days-before-stale: 0
        last-updated-user-type: 'non-collaborator'
        days-before-close: 999
